# Dockerfile.locust
FROM python:3.12-slim as builder

WORKDIR /app

RUN apt-get update && \
    apt-get install -y gcc build-essential libffi-dev libssl-dev && \
    rm -rf /var/lib/apt/lists/*

RUN pip install poetry==1.8.2

COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false && poetry install --only main --only dev

COPY . .

CMD ["poetry", "run", "locust", "-f", "locustfile.py", "--host", "http://localhost:8000"]
