services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file: ".env"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"


  postgres:
    container_name: ${POSTGRES_HOST}
    hostname: ${POSTGRES_HOST}
    image: postgres:latest
    env_file:
      - ./.env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
      start_interval: 3s
    volumes:
      - pgdata:/var/lib/postgresql/data

  locust:
    build:
      context: .
      dockerfile: Dockerfile.locust
    container_name: locust
    env_file: ".env"
    command: poetry run locust -f locustfile.py --host http://backend:8000
    ports:
      - "8089:8089"
    depends_on:
      backend:
        condition: service_started
    profiles:
      - locust

volumes:
  pgdata:
