"""add review table

Revision ID: ee49546de7d6
Revises: 76feb0f2ca65
Create Date: 2025-11-28 23:35:08.923544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee49546de7d6'
down_revision: Union[str, None] = '76feb0f2ca65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('product_rating', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk__reviews__product_id__products')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__reviews__user_id__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__reviews'))
    )
    op.create_index(op.f('ix__reviews__created_at_id'), 'reviews', ['created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__reviews__created_at_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
