"""add product_avg_rating

Revision ID: b096879319bb
Revises: ee49546de7d6
Create Date: 2026-01-20 02:26:39.210859

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b096879319bb"
down_revision: Union[str, None] = "ee49546de7d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_average_ratings",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("rating_1_count", sa.Integer(), nullable=False),
        sa.Column("rating_2_count", sa.Integer(), nullable=False),
        sa.Column("rating_3_count", sa.Integer(), nullable=False),
        sa.Column("rating_4_count", sa.Integer(), nullable=False),
        sa.Column("rating_5_count", sa.Integer(), nullable=False),
        sa.Column("rating_count", sa.Integer(), nullable=False),
        sa.Column("avg_rating", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk__product_average_ratings__product_id__products"),
        ),
        sa.PrimaryKeyConstraint("product_id", name=op.f("pk__product_average_ratings")),
    )
    op.add_column("reviews", sa.Column("agregated", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "agregated")
    op.drop_table("product_average_ratings")
    # ### end Alembic commands ###
